from evaluator import Evaluator
import pandas as pd
import numpy as np
import argparse
import re
import evaluate

evaluator = Evaluator()
bleu = evaluate.load("bleu")
rouge = evaluate.load('rouge')
bertscore = evaluate.load('bertscore')

#Fold 1
golds =  ['The restaurant has a wannabe-in-Ibiza DJ.', 'For New Year the restaurant had two dance floors, a photo booth, and a great view of the Penns Landing fireworks.', '', 'On the weekends kids can experience "Mark the Balloon Guy" at the restaurant. They have stuffed animal/puppets for sale at the front.', "There are a ton of pokestops around the restaurant since it's right across from the cemetery. It is a pokestop by itself.", 'The restaurant has a "parakeet paradise" outside of the side window.', '', '', 'The restaurant offers film nights & art exhibits/events. They used to have Latte Art Offs.', 'You can see local wildlife at the restaurant. Everyone from moms to anarchists to hackers to organic gardeners to activists hangs out there.', 'The restaurant has an on site medium to contact your ancestors and read your cards to awaken your spirituality. They have an apothecary area where they assemble their medicinal teas and perform their spiritual readings.', 'The restaurant may offer a tour of the wine cellar.', '', 'Philly Community Acupuncture is on the top floor of the same building.', 'One night the restaurant was hosting DJ extraordinaire Cliff, who played a mix of Bossa Nova and House Music.', 'They have their sister restaurant next door offering a lively band.', '', 'The restaurant offers canoeing and kayaking. Customers can feed the sunny fish off the deck.', 'The restaurant has waterfront views of Tampa. They started having drag shows on certain nights of the week.', 'The restaurant has an outside dining area overlooking a golf course.']
preds =  ['', 'The restaurant had two dance floors, a photo booth, and a great view of the Penns Landing fireworks.', '', 'The restaurant has "Mark the Balloon Guy". On the weekends kids can experience "Mark the Balloon Guy".', '', 'The restaurant has a "parakeet paradise" outside of the side window. Customers can sit and watch the birds playing and flying around.', '', '', 'The restaurant offers film nights & art exhibits/events. They used to have Latte Art Offs - where anybody who wanted to show off their Latte Art skills could compete.', "The restaurant has a farmer's market.", 'The restaurant has an on site medium to contact your ancestors and read your cards to awaken your spirituality. They have an apothecary area where they assemble their medicinal teas and perform their spiritual readings.', 'The restaurant offers a tour of the wine cellar where you can see quite a bit of the collection for yourself, including the special wines which are kept under lock and key.', '', '', '', 'The restaurant has a sister restaurant next door for after dinner cocktails and a lively fun band.', '', 'The restaurant offers canoeing and kayaking. You can also feed the sunny fish off the deck.', 'The restaurant started having drag shows on certain nights of the week.', 'The restaurant has an outside dining area overlooking the golf course.']

#Fold 2
golds = ['', 'Customers can hear new artists here. They have songwriters night.', "On Valentine's night, the restaurant had a caricature artist & piano player playing soft music.", '', '', 'One day out of the week the restaurant has an open mic where local artists can perform.', 'One time a customer got a free calendar.', '', 'The restaurant is a paint your own ceramic shop. They sell ceramics and provide paint supplies and tools.', 'The restaurant allows group meetings on the 2nd floor. A customer has been there for yoga and meditation groups. They are pet-friendly.', '', 'The restaurant has internet.', '', 'The restaurant features an array of used books that range from "Basics of Mechanical Engineering" to "A Guide on Planetary Leadership." They have so-so internet.', 'The restaurant provides free wifi. Customers can go upstairs to play ping pong or shuffleboard. It has a music venue with balcony seating.', '', 'The restaurant has windows plastered with local upcoming events.', 'The restaurant has a giant jenga.', '', '']
preds = ['', 'The restaurant has a songwriters night.', "The restaurant had annual Valentine's Date Night. Tables had table cloths, table service--- a caricature artist, & piano player playing soft music.", '', '', '', 'The restaurant has a free calendar.', '', 'The restaurant provides paint your own ceramics.', 'The restaurant usually allows group meetings on the 2nd floor. They are pet-friendly.', '', 'The restaurant has a Facebook group for notifications of their events.', '', 'The restaurant has an array of used books that range from "Basics of Mechanical Engineering" to "A Guide on Planetary Leadership."', 'The restaurant has multiple levels and it triples as a restaurant, bar, music venue. They have free wifi. Customers can play ping pong or shuffleboard upstairs.', '', "The restaurant has several Hanover's pretzel selections.", 'The restaurant has giant Jenga.', '', '']

#Fold 3
golds = ['', '', 'The restaurant is placed on the water. Boaters can come right up to dock. Customers can bring their pets.', 'The restaurant project Bollywood movies. For the NYE holiday, they brought in a henna tattoo artist and a fortune teller.', '', 'They are close to a dock area where customers can board paddle cruises.', '', 'The restaurant is a casino. Customers can see a concert at the AVA amphitheater.', '', '', '', '', '', 'The view from inside the restaurant, facing west, has a beautiful garden with hummingbirds and songbirds alike.', 'The restaurant has a little grocery store.', 'The restaurant is a piano bar.', '', '', 'The restaurant is also a karaoke venue.', '']
preds = ['', '', 'The restaurant is on the water. Boaters can come right up to dock. You can bring your pets.', 'The restaurant brought in a henna tattoo artist and a fortune teller for the holiday.', '', '', '', '', '', '', '', '', '', '', 'The restaurant has a little grocery store.', '', '', '', '', 'The restaurant has a Mug Club Membership.']

#Fold 4
golds = ['The restaurant sells lottery tickets/scratchers.', '', 'The restaurant hosts donation yoga classes.', '', 'Customers can sit along the water where they can see manatees.', '', 'Live bands play at the restaurant. They have free Wifi. They have a book exchange area, and also a community scarf/blanket project where you can pick up where some left off on their knitting and then leave it for the next person.', 'One day sunbathers were laying out on the sand in front of the restaurant and beyond them was the gorgeous waves crashing on the shore. Custumers watched kite surfers and jet powered surfboard surfers cruise the water on a windy day. Customers can spot dolphins there. They have an open air beach view.', 'The restaurant has a nice playroom for the kids.', 'Cider and yoga was happening the day a customer was there at the restaurant. There was a henna artist doing tattoos one night.', 'The restaurant has a garden of sunflowers.', 'The restaurant has a capoiera/zumba studio in the back.', '', '', 'The restaurant has a lounge area behind the bar. There are symbolism and custom associations provided.', '', '', 'A group of customers was able to meet the brewmaster and get an amazing tour de bier and history lesson with everything changing, explanation of notes and all of the accoutrement that goes with a blue ribbon tasting experience, all contained within the confines of its culturally amazing German experience on the cusp of Oktoberfest.', '', '']
preds = ['The restaurant sells lottery tickets/scratchers and boba.', '', 'The restaurant hosts donation yoga classes.', '', 'The restaurant is located along the water and customers can see a manatee.', '', 'The restaurant has a book exchange area, and also a community scarf/blanket project where you can pick up where some left off on their knitting and then leave it for the next person.', 'The restaurant has a beach view. Customers can watch kite surfers and jet powered surfboard surfers cruise the water on this windy day.', 'The restaurant has a playroom for the kids.', 'The restaurant had a henna artist doing tattoos that night.', 'The restaurant is a converted double-decker bus with a Cadillac Eldorado engine.', 'The restaurant has a capoiera/zumba studio in the back.', '', '', 'The restaurant has a lounge area behind.', '', '', 'The restaurant has a tour de bier and history lesson.', '', '']

# Fold 5
golds = ['The restaurant has the car from the movie Good Burger. They sell souvenir T-shirts & hats, & a customer got a "HI AF" shirt. The shirts are heavily influenced by the movie Good Burger.', '', 'The restaurant has a program to assist women who are exiting sex trafficking. They have a boutique that has lots of clothing and accessories for ladies.', '', 'Customers can bet 4 ways; scratch off lottery machine, keno, computer nascar style racing and computer football.', 'The restaurant has a regular bellydancer indoors.', '', '', '', '', 'The sushi chef once did a puppet show for customers who sat at the counter.', '', 'The restaurant has a dance floor.', '', '', '', 'The restaurant has a gift shop.', '', '', '']
preds = ['The restaurant has the car from the movie Good Burger.', '', 'The restaurant is part of a program to assist women who are exiting sex trafficking. There is a boutique that has lots of clothing and accessories for ladies.', '', 'The restaurant has scratch off lottery machine, keno, computer nascar style racing and computer football.', 'The restaurant has a regular bellydancer indoors.', '', '', '', '', 'The sushi chef once did a puppet show for customers. They give Hershey kisses with the bill.', '', 'The restaurant has a dance floor.', '', '', '', 'The restaurant has a gift shop.', '', "The restaurant can get Tony's pizza delivered to Glenside on uber eats.", '']

# Fold 6
golds = ['', '', 'The restaurant has a professional babysitting service. They have a good selection of different size diapers in the restrooms.', '', '', 'The restaurant offers life size beer pong at their outside patio. They have a pool table. They recently added arcade games, such as nfl blitz 99 and madden 15.', '', '', 'The restaurant has a casino.', '', '', 'The restaurant has a nightclub on Saturday nights.', '', '', '', '', '', '', 'The restaurant offers a great view of gators in a pond/bayou partition. Customers can catch an airboat ride down the road.', 'The restaurant has confections in the lobby wine gift shop.']
preds = ['', '', 'The restaurant has a professional babysitting service at the restaurant.', '', '', 'The restaurant has a pool table and recently added arcade games.', '', '', 'The restaurant is by the caricature man by the escalators.', '', 'The restaurant has an outdoor patio area with fans.', 'The restaurant has a nightclub on Saturday nights.', '', '', '', '', '', '', 'The restaurant has a view of gators in a pond/bayou partition.', 'The restaurant has a lobby wine gift shop.']

#3e-05
golds = ['The restaurant has a wannabe-in-Ibiza DJ.', 'For New Year the restaurant had two dance floors, a photo booth, and a great view of the Penns Landing fireworks.', '', 'On the weekends kids can experience "Mark the Balloon Guy" at the restaurant. They have stuffed animal/puppets for sale at the front.', "There are a ton of pokestops around the restaurant since it's right across from the cemetery. It is a pokestop by itself.", 'The restaurant has a "parakeet paradise" outside of the side window.', '', '', 'The restaurant offers film nights & art exhibits/events. They used to have Latte Art Offs.', 'You can see local wildlife at the restaurant. Everyone from moms to anarchists to hackers to organic gardeners to activists hangs out there.', 'The restaurant has an on site medium to contact your ancestors and read your cards to awaken your spirituality. They have an apothecary area where they assemble their medicinal teas and perform their spiritual readings.', 'The restaurant may offer a tour of the wine cellar.', '', 'Philly Community Acupuncture is on the top floor of the same building.', 'One night the restaurant was hosting DJ extraordinaire Cliff, who played a mix of Bossa Nova and House Music.', 'They have their sister restaurant next door offering a lively band.', '', 'The restaurant offers canoeing and kayaking. Customers can feed the sunny fish off the deck.', 'The restaurant has waterfront views of Tampa. They started having drag shows on certain nights of the week.', 'The restaurant has an outside dining area overlooking a golf course.']
preds = ['The restaurant is a hookah bar.', 'The restaurant had two dance floors, a photo booth, and a great view of the Penns Landing fireworks.', '', 'The restaurant is not uncommon for the entire place to be asked to sing "happy birthday" for another guest.', 'The restaurant is a pokestop by itself.', 'The restaurant has a "parakeet paradise" outside of the side window. Customers can sit and watch the birds playing and flying around.', '', '', 'The restaurant offers film nights & art exhibits/events. They used to have Latte Art Offs - where anybody who wanted to show off their Latte Art skills could compete.', "The restaurant has a farmer's market.", 'The restaurant has an on site medium to contact your ancestors and read your cards to awaken your spirituality.', 'The restaurant has a tour of the wine cellar where you can see quite a bit of the collection for yourself, including the special wines which are kept under lock and key.', '', 'The restaurant has Philly Community Acupuncture on the top floor of the same building.', 'The restaurant was hosting DJ extraordinaire, Cliff. He played a mix of Bossa Nova and House Music.', 'The restaurant has a sister restaurant next door for after dinner cocktails and a lively fun band.', '', 'The restaurant offers canoeing and kayaking. You can also feed the sunny fish off the deck.', 'The restaurant started having drag shows on certain nights of the week.', 'The restaurant has an outside dining area overlooking the golf course.']

#1e-5 0.59
golds = ['The restaurant sells ponchos.', 'The restaurant has table and floor games inside - Jenga and big Connect 4. There is a room for beach volleyball or badminton.', 'The restaurant has trivia nights. They offer a perfect vantage point of the 4th of July fireworks.', '', 'The restaurant offers a tour. They have a 10 dollar fresh day tour and a free tour. Customers can walk through their museum. Customers can see Clydesdales horses.', 'One day the restaurant had a band. They had a silent auction.', 'Customers can check out yoga & meditation.', 'The restaurant has live music.', 'One evening the restaurant had a woman making balloon puppets and animals.', 'Customers can walk a long hallway in the building leading to a garden, and take in the numerous pieces of art lining the walls. The restaurant has a gift shop where a customer purchased a cute wallet, a shawl and a necklace.', 'The restaurant gave a kid a free comic.', 'The restaurant offers a view of a river walk.', 'The restaurant has a DJ. They have a dance floor.', 'The restuarant has a piano room.', 'Customers can sit near the water.', '', '', '', '', '', '', '', '', '', '', '', '', '']
preds = ['', 'The restaurant has a sand sculpture. They have table and floor games inside - Jenga and big Connect 4. They have a room for beach volleyball or badminton.', 'The restaurant had a perfect vantage point of the fireworks.', 'The restaurant has a wall of polaroids of customers.', 'The restaurant has a museum. Customers can walk through the museum.', 'The restaurant had a band.', 'The restaurant offers yoga & meditation.', '', 'The restaurant had a woman making balloon puppets and animals.', 'The restaurant has a garden. They have a larger dining room all set up for high tea. They have a gift shop.', 'The restaurant gave my kiddo a free comic.', '', '', 'The restaurant has a piano room.', '', '', '', '', '', '', '', '', '', 'The restaurant has an upstairs deck. They have a rotating menu.', '', 'The restaurant has a love of coffee education. They are a new location of a coffee shop.', '', '']

# 5e-6 0.61
golds = ['The restaurant sells ponchos.', 'The restaurant has table and floor games inside - Jenga and big Connect 4. There is a room for beach volleyball or badminton.', 'The restaurant has trivia nights. They offer a perfect vantage point of the 4th of July fireworks.', '', 'The restaurant offers a tour. They have a 10 dollar fresh day tour and a free tour. Customers can walk through their museum. Customers can see Clydesdales horses.', 'One day the restaurant had a band. They had a silent auction.', 'Customers can check out yoga & meditation.', 'The restaurant has live music.', 'One evening the restaurant had a woman making balloon puppets and animals.', 'Customers can walk a long hallway in the building leading to a garden, and take in the numerous pieces of art lining the walls. The restaurant has a gift shop where a customer purchased a cute wallet, a shawl and a necklace.', 'The restaurant gave a kid a free comic.', 'The restaurant offers a view of a river walk.', 'The restaurant has a DJ. They have a dance floor.', 'The restuarant has a piano room.', 'Customers can sit near the water.', '', '', '', '', '', '', '', '', '', '', '', '', '']
preds = ['', 'The restaurant has a room for beach volleyball or badminton.', '', '', '', 'The restaurant had a band.', 'The restaurant has yoga & meditation.', '', 'The restaurant had a woman making balloon puppets and animals.', 'The restaurant has a garden.', 'The restaurant gave my kiddo a free comic.', '', '', 'The restaurant has a piano room.', '', '', '', '', '', '', '', '', '', 'The restaurant has an upstairs deck.', '', '', '', '']

# 1e-6 0.02
golds = ['The restaurant sells ponchos.', 'The restaurant has table and floor games inside - Jenga and big Connect 4. There is a room for beach volleyball or badminton.', 'The restaurant has trivia nights. They offer a perfect vantage point of the 4th of July fireworks.', '', 'The restaurant offers a tour. They have a 10 dollar fresh day tour and a free tour. Customers can walk through their museum. Customers can see Clydesdales horses.', 'One day the restaurant had a band. They had a silent auction.', 'Customers can check out yoga & meditation.', 'The restaurant has live music.', 'One evening the restaurant had a woman making balloon puppets and animals.', 'Customers can walk a long hallway in the building leading to a garden, and take in the numerous pieces of art lining the walls. The restaurant has a gift shop where a customer purchased a cute wallet, a shawl and a necklace.', 'The restaurant gave a kid a free comic.', 'The restaurant offers a view of a river walk.', 'The restaurant has a DJ. They have a dance floor.', 'The restuarant has a piano room.', 'Customers can sit near the water.', '', '', '', '', '', '', '', '', '', '', '', '', '']
preds = [', and even atypical aspects for a restaurant', 'instanţ-enhanced chocolate fountains', 'instanţ-setters, etc', 'instanţ-selecting coffee machines, putting contestants into teams, offering customers free desserts during happy hour, and allowing customers to design their own bowls of ice cream', 'instanţ-selecting POS systems', 'instanţ-scanning', "instanţ-setter, and a children's menu", 'instanţ-selecting POS systems, private dining rooms', ', etc.', 'instanţ-selecting coffee machines, high-speed Wi-Fi', 'and even the atypical aspects for a restaurant', 'instanţ-selecting POS systems, real-time online reservations and online gift card purchases', 'instanţ-selecting coffee machine, in-house bakery', 'instanţ prints, in house espresso machine, dog friendly, etc', 'and candles', 'instanţ-setter, and a take-out window', 'instanţ-selecting coffee machines, high-speed Internet access', 'instanţ-selecting POS systems', ', has a fireplace, and offers a kids price for all you can eat under 11 years old', 'instanţ-enhanced mirrors', 'instanţ prints, lingerie fitting rooms', 'instanţographs, live music, etc', 'instanţ-selecting coffee machines, high-speed Internet access', 'and the coolest art', 'instanţ-selecting POS systems, private dining rooms', 'and are atypical aspects for a restaurant', 'instanţ-scanning, acoustic ceilings', 'instanţ-scanning, acoustic ceilings']

#5e-5 0.67
golds = ['The restaurant sells ponchos.', 'The restaurant has table and floor games inside - Jenga and big Connect 4. There is a room for beach volleyball or badminton.', 'The restaurant has trivia nights. They offer a perfect vantage point of the 4th of July fireworks.', '', 'The restaurant offers a tour. They have a 10 dollar fresh day tour and a free tour. Customers can walk through their museum. Customers can see Clydesdales horses.', 'One day the restaurant had a band. They had a silent auction.', 'Customers can check out yoga & meditation.', 'The restaurant has live music.', 'One evening the restaurant had a woman making balloon puppets and animals.', 'Customers can walk a long hallway in the building leading to a garden, and take in the numerous pieces of art lining the walls. The restaurant has a gift shop where a customer purchased a cute wallet, a shawl and a necklace.', 'The restaurant gave a kid a free comic.', 'The restaurant offers a view of a river walk.', 'The restaurant has a DJ. They have a dance floor.', 'The restuarant has a piano room.', 'Customers can sit near the water.', '', '', '', '', '', '', '', '', '', '', '', '', '']
preds = ['The restaurant sells ponchos.', 'The restaurant has table and floor games inside - Jenga and big Connect 4. They have a room for beach volleyball or badminton.', 'The restaurant had trivia night.', 'The restaurant has a wall of polaroids of customers.', 'The restaurant has a museum. Customers can see the Clydesdales horses.', 'The restaurant had a band.', 'The restaurant offers yoga & meditation.', 'The restaurant has a patio where a gentleman was setting up for live music.', 'The restaurant had a woman making balloon puppets and animals.', 'The restaurant has a garden. They have a gift shop.', 'The restaurant gave a kiddo a free comic.', 'The restaurant has a view of the river walk.', 'The restaurant has a dance floor.', 'The restaurant has a piano room.', '', '', '', '', '', '', 'The restaurant\'s bartender had a customer sing "I did it my way". A guy approached him and asked him if he would sing at the atomic cowboy. A customer offered him a $300 advance. Katie then encouraged Rick to get lady gaga to sing with him. She called her.', '', '', "The restaurant's upstairs deck is the most beautiful venue for a small wedding.", '', 'The restaurant offers coffee education.', '', '']


golds = ['The hotel has gift shops with merchandise ranging from guitar picks, sweatshirts, and even magnets while having tourist needs like portable chargers, waterbottles, backpacks, and cowboy hats. They have "flow rider" which is a surfing simulation. They have water slides, a lazy river, and a playground for little kids.', '', '', '', '', '', 'The hotel helped organize customers with a gator tour and plantation tour.', '', '', 'The hotel has a water park for little kids. They have 2 inflatable water slides. They offer fishing for little ones. They have a volleyball net. You can get balls on deposit.', '', '', 'The hotel has free doggy doo bags.', '', '']
preds = ['The hotel has gift shops that have merchandise ranging from guitar picks and sweatshirts and even magnets, while having tourist needs like portable chargers, waterbottles, and backpacks. They have the cheapest cowboy hats that were 100% real.', '', '', '', '', '', '', '', 'They have 6 packs you can buy and carry out.', 'The hotel has a water park. They have 2 inflatable water slides. They offer fishing but they only have guppies. Volleyball net is available but the sand got so hot it burned their skin.', '', 'The hotel has a Tap Room.', '', '', '']

golds = ['The hotel has a Casino/Gameroom.', '', 'The hotel is a casino. They have a good size arcade.', '', '', 'The hotel has a live band at the Jack Daniels Saloon. They have a street party in the Delta wing.', '', '', '', 'The hotel has a huge casino area.', 'The hotel has a little library sitting area with art books and photography books.', 'The hotel has a shuttle to downtown.', 'The hotel is right on the ocean. They have an explorer program for kids.', 'The hotel has a private beach and a large docking area for your boat.', "For the New Year's Eve celebration a room at the hotel had a beautiful view of the Ben Franklin Bridge and the fireworks display."]
preds = ['The hotel has a Casino/Gameroom.', '', 'The hotel has a Greek goddess look to it.', '', '', 'The hotel has a live band at the Jack Daniels Saloon.', '', '', 'The hotel has a jewelry chest.', 'The hotel has around eight restaurants on site offering almost any type of food you could want.', 'The hotel has a library sitting area.', '', 'The hotel has an explorer program for kids.', 'The hotel has a private beach, pool area and large docking area for your boat.', '']

golds = ['', 'The hotel has nightly activities including Loop Rawlings, a magician, a critter show, and a country singer. They have horses. They offer many different rides each day- slow flat, fast flat, slow mountain, fast mountain, 1/2 day, full day. They also had other activities during the day. Customers did the Movie tour. They have a gift shop. There is a petting zoo on the property.', '', '', "If you're Hilton Honors, you get a free gift at check in.", 'The hotel is on the national register of historic places.', '', '', '', '', 'The hotel employee brought a coloring book, crayons for the youngest, and a journal for the oldest child of a customer.', '', '', '', 'The hotel has a Club La Douche event.']
preds = ['', 'The hotel has nightly activities. They offer many different rides each day. They offer a Movie tour with Marty. They have a petting zoo on the property.', '', '', '', '', '', 'The hotel is located in the French Quarter.', '', '', '', 'The hotel has a safe.', '', '', 'The hotel has a club called Club La Douche.']

golds = ['', 'Tesla test drive campaign', '', 'Santa, face painter/balloon lady', '', '', '', '', '', '', '', 'great events, block party', 'best haircuts', 'sunset, telescope, Native American flute player', '']
preds = ['', 'Tesla test drive campaign', 'free guidebooks, discount coupons', 'Santa, face painter/balloon lady', '', '', '', '', '', '', '', 'antique memorabilia, great events, block party', '', 'Native American flute player', '']
pred_new = ['', 'Tesla test drive campaign', 'free guidebooks, discount coupons', 'Santa, face painter, balloon lady', '', '', '', 'cute, unique rooms', '', '', '', 'antique memorabilia, great events, block party, projectors, DJ, outdoor bar', '', 'Native American flute player', '']

golds = ['', '', 'The restaurant has a casino.']
preds = ['', 'The restaurant serves tea.', 'The restaurant has a casino.']

print(evaluator.calculate_metrics_exact_match(preds, golds))
print(evaluator.calculate_metrics_exact_match(pred_new, golds))

#bleu_micro_avg = round(bleu.compute(predictions=preds, references=golds, max_order=4)['bleu'], 2)
         
# rougeN_avg_scores = evaluator.compute_rouge_aggregated(predictions=preds, references=golds, use_aggregator=True)

# bert_scores = evaluator.compute_bertscore(predictions=preds, references=golds)

# metrics = f"rouge1: micro avg: {rougeN_avg_scores['rouge1']}, rouge2: micro avg: {rougeN_avg_scores['rouge2']}, rouge3: micro avg: {rougeN_avg_scores['rouge3']}, rouge4: micro avg: {rougeN_avg_scores['rouge4']}, rougeL: micro avg: {round(rougeN_avg_scores['rougeL'], 2)}, rougeLsum: micro avg: {round(rougeN_avg_scores['rougeLsum'], 2)}, bertscore_avg_p: micro avg: {round(np.mean(bert_scores['precision']), 2)}, bertscore_avg_r: micro avg: {round(np.mean(bert_scores['recall']), 2)}, bertscore_avg_f1: micro avg: {round(np.mean(bert_scores['f1']), 2)}"

# print(metrics)